[Options]
windowrunonstartup = False
windowwidth = 250
windowheight = 130
windowexpandedwidth = 250
windowexpandedheight = 260
windowx = 3070
windowy = 518
windowisexpanded = 1
windowbackground = #8000ff
windowbgistransparent = True
windowtext = #000000
windowtextistransparent = False
windowalwaysontop = False

